# Run uv sync if the uv.lock file is newer than the last sync timestamp
function(sync_uv_if_needed)
   set(LOCK_FILE "${CMAKE_SOURCE_DIR}/uv.lock")
   set(SYNC_TIMESTAMP_FILE "${CMAKE_BINARY_DIR}/uv_sync_timestamp")
   if(EXISTS "${LOCK_FILE}")
      file(TIMESTAMP "${LOCK_FILE}" LOCK_TIMESTAMP)
      if(EXISTS "${SYNC_TIMESTAMP_FILE}")
         file(TIMESTAMP "${SYNC_TIMESTAMP_FILE}" SYNC_TIMESTAMP)
         if(LOCK_TIMESTAMP STRGREATER SYNC_TIMESTAMP)
            message(STATUS "uv.lock is newer than last sync. Running uv sync...")
            execute_process(COMMAND ${UV_EXECUTABLE} sync
               WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
            file(WRITE "${SYNC_TIMESTAMP_FILE}" "")
         else()
            message(STATUS "uv.lock has not changed since last sync. Skipping uv sync.")
         endif()
      else()
         message(STATUS "No previous uv sync timestamp found. Running uv sync...")
         execute_process(COMMAND ${UV_EXECUTABLE} sync
            WORKING_DIRECTORY ${CMAKE_SOURCE_DIR})
         file(WRITE "${SYNC_TIMESTAMP_FILE}" "")
      endif()
   else()
      message(WARNING "uv.lock file not found. Cannot determine if uv sync is needed.")
   endif()
endfunction()
